# ISO3166 python dict 
# oficial list in http://www.iso.org/iso/iso_3166_code_lists

{'CN ': 'China', 'IN ': 'India', 'US ': 'United States', 'ID ': 'Indonesia', 'PK ': 'Pakistan', 'BR ': 'Brazil', 'NG ': 'Niger', 'BD ': 'Bangladesh', 'RU ': 'Russia', 'MX ': 'Mexico', 'JP ': 'Japan', 'ET ': 'Ethiopia', 'PH ': 'Philippines', 'EG ': 'Egypt', 'VN ': 'Vietnam', 'CD ': 'DR Congo', 'TR ': 'Turkey', 'IR ': 'Iran', 'DE ': 'Germany', 'TH ': 'Thailand', 'GB ': 'United Kingdom', 'FR ': 'Mayotte', 'IT ': 'Italy', 'TZ ': 'Tanzania', 'ZA ': 'South Africa', 'MM ': 'Myanmar', 'KE ': 'Kenya', 'KR ': 'South Korea', 'CO ': 'Colombia', 'ES ': 'Spain', 'UG ': 'Uganda', 'AR ': 'Argentina', 'DZ ': 'Algeria', 'SD ': 'Sudan', 'UA ': 'Ukraine', 'IQ ': 'Iraq', 'AF ': 'Afghanistan', 'PL ': 'Poland', 'CA ': 'Canada', 'MA ': 'Morocco', 'SA ': 'Saudi Arabia', 'UZ ': 'Uzbekistan', 'PE ': 'Peru', 'AO ': 'Angola', 'MY ': 'Malaysia', 'MZ ': 'Mozambique', 'GH ': 'Ghana', 'YE ': 'Yemen', 'NP ': 'Nepal', 'VE ': 'Venezuela', 'MG ': 'Madagascar', 'CM ': 'Cameroon', 'CI ': "Côte d'Ivoire", 'KP ': 'North Korea', 'AU ': 'Australia', 'TW ': 'Taiwan', 'LK ': 'Sri Lanka', 'BF ': 'Burkina Faso', 'ML ': 'Mali', 'RO ': 'Romania', 'MW ': 'Malawi', 'CL ': 'Chile', 'KZ ': 'Kazakhstan', 'ZM ': 'Zambia', 'GT ': 'Guatemala', 'EC ': 'Ecuador', 'SY ': 'Syria', 'NL ': 'Sint Maarten', 'SN ': 'Senegal', 'KH ': 'Cambodia', 'TD ': 'Chad', 'SO ': 'Somalia', 'ZW ': 'Zimbabwe', 'GN ': 'Guinea', 'RW ': 'Rwanda', 'BJ ': 'Benin', 'BI ': 'Burundi', 'TN ': 'Tunisia', 'BO ': 'Bolivia', 'BE ': 'Belgium', 'HT ': 'Haiti', 'CU ': 'Cuba', 'SS ': 'South Sudan', 'DO ': 'Dominican Republic', 'CZ ': 'Czech Republic (Czechia)', 'GR ': 'Greece', 'JO ': 'Jordan', 'PT ': 'Portugal', 'AZ ': 'Azerbaijan', 'SE ': 'Sweden', 'HN ': 'Honduras', 'AE ': 'United Arab Emirates', 'HU ': 'Hungary', 'TJ ': 'Tajikistan', 'BY ': 'Belarus', 'AT ': 'Austria', 'PG ': 'Papua New Guinea', 'RS ': 'Serbia', 'IL ': 'Israel', 'CH ': 'Switzerland', 'TG ': 'Togo', 'SL ': 'Sierra Leone', 'HK ': 'Hong Kong', 'LA ': 'Laos', 'PY ': 'Paraguay', 'BG ': 'Bulgaria', 'LY ': 'Libya', 'LB ': 'Lebanon', 'NI ': 'Nicaragua', 'KG ': 'Kyrgyzstan', 'SV ': 'El Salvador', 'TM ': 'Turkmenistan', 'SG ': 'Singapore', 'DK ': 'Denmark', 'FI ': 'Finland', 'CG ': 'Congo', 'SK ': 'Slovakia', 'NO ': 'Norway', 'OM ': 'Oman', 'PS ': 'State of Palestine', 'CR ': 'Costa Rica', 'LR ': 'Liberia', 'IE ': 'Ireland', 'CF ': 'Central African Republic', 'NZ ': 'New Zealand', 'MR ': 'Mauritania', 'PA ': 'Panama', 'KW ': 'Kuwait', 'HR ': 'Croatia', 'MD ': 'Moldova', 'GE ': 'Georgia', 'ER ': 'Eritrea', 'UY ': 'Uruguay', 'BA ': 'Bosnia and Herzegovina', 'MN ': 'Mongolia', 'AM ': 'Armenia', 'JM ': 'Jamaica', 'QA ': 'Qatar', 'AL ': 'Albania', 'PR ': 'Puerto Rico', 'LT ': 'Lithuania', 'NA ': 'Namibia', 'GM ': 'Gambia', 'BW ': 'Botswana', 'GA ': 'Gabon', 'LS ': 'Lesotho', 'MK ': 'North Macedonia', 'SI ': 'Slovenia', 'GW ': 'Guinea-Bissau', 'LV ': 'Latvia', 'BH ': 'Bahrain', 'GQ ': 'Equatorial Guinea', 'TT ': 'Trinidad and Tobago', 'EE ': 'Estonia', 'TL ': 'Timor-Leste', 'MU ': 'Mauritius', 'CY ': 'Cyprus', 'SZ ': 'Eswatini', 'DJ ': 'Djibouti', 'FJ ': 'Fiji', 'RE ': 'Réunion', 'KM ': 'Comoros', 'GY ': 'Guyana', 'BT ': 'Bhutan', 'SB ': 'Solomon Islands', 'MO ': 'Macao', 'ME ': 'Montenegro', 'LU ': 'Luxembourg', 'EH ': 'Western Sahara', 'SR ': 'Suriname', 'CV ': 'Cabo Verde', 'MV ': 'Maldives', 'MT ': 'Malta', 'BN ': 'Brunei', 'BZ ': 'Belize', 'BS ': 'Bahamas', 'MQ ': 'Martinique', 'IS ': 'Iceland', 'VU ': 'Vanuatu', 'GF ': 'French Guiana', 'BB ': 'Barbados', 'NC ': 'New Caledonia', 'PF ': 'French Polynesia', 'ST ': 'Sao Tome & Principe', 'WS ': 'Samoa', 'LC ': 'Saint Lucia', 'GU ': 'Guam', 'KI ': 'Kiribati', 'FM ': 'Micronesia', 'GD ': 'Grenada', 'VC ': 'St. Vincent & Grenadines', 'AW ': 'Aruba', 'TO ': 'Tonga', 'VI ': 'U.S. Virgin Islands', 'SC ': 'Seychelles', 'AG ': 'Antigua and Barbuda', 'IM ': 'Isle of Man', 'AD ': 'Andorra', 'DM ': 'Dominica', 'KY ': 'Cayman Islands', 'BM ': 'Bermuda', 'MH ': 'Marshall Islands', 'MP ': 'Northern Mariana Islands', 'GL ': 'Greenland', 'AS ': 'American Samoa', 'KN ': 'Saint Kitts & Nevis', 'FO ': 'Faeroe Islands', 'MC ': 'Monaco', 'TC ': 'Turks and Caicos', 'MF ': 'Saint Martin', 'LI ': 'Liechtenstein', 'SM ': 'San Marino', 'GI ': 'Gibraltar', 'VG ': 'British Virgin Islands', 'BQ ': 'Caribbean Netherlands', 'PW ': 'Palau', 'CK ': 'Cook Islands', 'AI ': 'Anguilla', 'TV ': 'Tuvalu', 'WF ': 'Wallis & Futuna', 'NR ': 'Nauru', 'BL ': 'Saint Barthelemy', 'SH ': 'Saint Helena', 'PM ': 'Saint Pierre & Miquelon', 'MS ': 'Montserrat', 'FK ': 'Falkland Islands', 'NU ': 'Niue', 'TK ': 'Tokelau', 'VA ': 'Holy See'}

countries = {
	'AF': 'AFGHANISTAN',
	'AX': 'ÅLAND ISLANDS',
	'AL': 'ALBANIA',
	'DZ': 'ALGERIA',
	'AS': 'AMERICAN SAMOA',
	'AD': 'ANDORRA',
	'AO': 'ANGOLA',
	'AI': 'ANGUILLA',
	'AQ': 'ANTARCTICA',
	'AG': 'ANTIGUA AND BARBUDA',
	'AR': 'ARGENTINA',
	'AM': 'ARMENIA',
	'AW': 'ARUBA',
	'AU': 'AUSTRALIA',
	'AT': 'AUSTRIA',
	'AZ': 'AZERBAIJAN',
	'BS': 'BAHAMAS',
	'BH': 'BAHRAIN',
	'BD': 'BANGLADESH',
	'BB': 'BARBADOS',
	'BY': 'BELARUS',
	'BE': 'BELGIUM',
	'BZ': 'BELIZE',
	'BJ': 'BENIN',
	'BM': 'BERMUDA',
	'BT': 'BHUTAN',
	'BO': 'BOLIVIA, PLURINATIONAL STATE OF',
	'BQ': 'BONAIRE, SINT EUSTATIUS AND SABA',
	'BA': 'BOSNIA AND HERZEGOVINA',
	'BW': 'BOTSWANA',
	'BV': 'BOUVET ISLAND',
	'BR': 'BRAZIL',
	'IO': 'BRITISH INDIAN OCEAN TERRITORY',
	'BN': 'BRUNEI DARUSSALAM',
	'BG': 'BULGARIA',
	'BF': 'BURKINA FASO',
	'BI': 'BURUNDI',
	'KH': 'CAMBODIA',
	'CM': 'CAMEROON',
	'CA': 'CANADA',
	'CV': 'CAPE VERDE',
	'KY': 'CAYMAN ISLANDS',
	'CF': 'CENTRAL AFRICAN REPUBLIC',
	'TD': 'CHAD',
	'CL': 'CHILE',
	'CN': 'CHINA',
	'CX': 'CHRISTMAS ISLAND',
	'CC': 'COCOS (KEELING) ISLANDS',
	'CO': 'COLOMBIA',
	'KM': 'COMOROS',
	'CG': 'CONGO',
	'CD': 'CONGO, THE DEMOCRATIC REPUBLIC OF THE',
	'CK': 'COOK ISLANDS',
	'CR': 'COSTA RICA',
	'CI': 'CÔTE D\'IVOIRE',
	'HR': 'CROATIA',
	'CU': 'CUBA',
	'CW': 'CURAÇAO',
	'CY': 'CYPRUS',
	'CZ': 'CZECH REPUBLIC',
	'DK': 'DENMARK',
	'DJ': 'DJIBOUTI',
	'DM': 'DOMINICA',
	'DO': 'DOMINICAN REPUBLIC',
	'EC': 'ECUADOR',
	'EG': 'EGYPT',
	'SV': 'EL SALVADOR',
	'GQ': 'EQUATORIAL GUINEA',
	'ER': 'ERITREA',
	'EE': 'ESTONIA',
	'ET': 'ETHIOPIA',
	'FK': 'FALKLAND ISLANDS (MALVINAS)',
	'FO': 'FAROE ISLANDS',
	'FJ': 'FIJI',
	'FI': 'FINLAND',
	'FR': 'FRANCE',
	'GF': 'FRENCH GUIANA',
	'PF': 'FRENCH POLYNESIA',
	'TF': 'FRENCH SOUTHERN TERRITORIES',
	'GA': 'GABON',
	'GM': 'GAMBIA',
	'GE': 'GEORGIA',
	'DE': 'GERMANY',
	'GH': 'GHANA',
	'GI': 'GIBRALTAR',
	'GR': 'GREECE',
	'GL': 'GREENLAND',
	'GD': 'GRENADA',
	'GP': 'GUADELOUPE',
	'GU': 'GUAM',
	'GT': 'GUATEMALA',
	'GG': 'GUERNSEY',
	'GN': 'GUINEA',
	'GW': 'GUINEA-BISSAU',
	'GY': 'GUYANA',
	'HT': 'HAITI',
	'HM': 'HEARD ISLAND AND MCDONALD ISLANDS',
	'VA': 'HOLY SEE (VATICAN CITY STATE)',
	'HN': 'HONDURAS',
	'HK': 'HONG KONG',
	'HU': 'HUNGARY',
	'IS': 'ICELAND',
	'IN': 'INDIA',
	'ID': 'INDONESIA',
	'IR': 'IRAN, ISLAMIC REPUBLIC OF',
	'IQ': 'IRAQ',
	'IE': 'IRELAND',
	'IM': 'ISLE OF MAN',
	'IL': 'ISRAEL',
	'IT': 'ITALY',
	'JM': 'JAMAICA',
	'JP': 'JAPAN',
	'JE': 'JERSEY',
	'JO': 'JORDAN',
	'KZ': 'KAZAKHSTAN',
	'KE': 'KENYA',
	'KI': 'KIRIBATI',
	'KP': 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF',
	'KR': 'KOREA, REPUBLIC OF',
	'KW': 'KUWAIT',
	'KG': 'KYRGYZSTAN',
	'LA': 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC',
	'LV': 'LATVIA',
	'LB': 'LEBANON',
	'LS': 'LESOTHO',
	'LR': 'LIBERIA',
	'LY': 'LIBYAN ARAB JAMAHIRIYA',
	'LI': 'LIECHTENSTEIN',
	'LT': 'LITHUANIA',
	'LU': 'LUXEMBOURG',
	'MO': 'MACAO',
	'MK': 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF',
	'MG': 'MADAGASCAR',
	'MW': 'MALAWI',
	'MY': 'MALAYSIA',
	'MV': 'MALDIVES',
	'ML': 'MALI',
	'MT': 'MALTA',
	'MH': 'MARSHALL ISLANDS',
	'MQ': 'MARTINIQUE',
	'MR': 'MAURITANIA',
	'MU': 'MAURITIUS',
	'YT': 'MAYOTTE',
	'MX': 'MEXICO',
	'FM': 'MICRONESIA, FEDERATED STATES OF',
	'MD': 'MOLDOVA, REPUBLIC OF',
	'MC': 'MONACO',
	'MN': 'MONGOLIA',
	'ME': 'MONTENEGRO',
	'MS': 'MONTSERRAT',
	'MA': 'MOROCCO',
	'MZ': 'MOZAMBIQUE',
	'MM': 'MYANMAR',
	'NA': 'NAMIBIA',
	'NR': 'NAURU',
	'NP': 'NEPAL',
	'NL': 'NETHERLANDS',
	'NC': 'NEW CALEDONIA',
	'NZ': 'NEW ZEALAND',
	'NI': 'NICARAGUA',
	'NE': 'NIGER',
	'NG': 'NIGERIA',
	'NU': 'NIUE',
	'NF': 'NORFOLK ISLAND',
	'MP': 'NORTHERN MARIANA ISLANDS',
	'NO': 'NORWAY',
	'OM': 'OMAN',
	'PK': 'PAKISTAN',
	'PW': 'PALAU',
	'PS': 'PALESTINIAN TERRITORY, OCCUPIED',
	'PA': 'PANAMA',
	'PG': 'PAPUA NEW GUINEA',
	'PY': 'PARAGUAY',
	'PE': 'PERU',
	'PH': 'PHILIPPINES',
	'PN': 'PITCAIRN',
	'PL': 'POLAND',
	'PT': 'PORTUGAL',
	'PR': 'PUERTO RICO',
	'QA': 'QATAR',
	'RE': 'RÉUNION',
	'RO': 'ROMANIA',
	'RU': 'RUSSIAN FEDERATION',
	'RW': 'RWANDA',
	'BL': 'SAINT BARTHÉLEMY',
	'SH': 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA',
	'KN': 'SAINT KITTS AND NEVIS',
	'LC': 'SAINT LUCIA',
	'MF': 'SAINT MARTIN (FRENCH PART)',
	'PM': 'SAINT PIERRE AND MIQUELON',
	'VC': 'SAINT VINCENT AND THE GRENADINES',
	'WS': 'SAMOA',
	'SM': 'SAN MARINO',
	'ST': 'SAO TOME AND PRINCIPE',
	'SA': 'SAUDI ARABIA',
	'SN': 'SENEGAL',
	'RS': 'SERBIA',
	'SC': 'SEYCHELLES',
	'SL': 'SIERRA LEONE',
	'SG': 'SINGAPORE',
	'SX': 'SINT MAARTEN (DUTCH PART)',
	'SK': 'SLOVAKIA',
	'SI': 'SLOVENIA',
	'SB': 'SOLOMON ISLANDS',
	'SO': 'SOMALIA',
	'ZA': 'SOUTH AFRICA',
	'GS': 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
	'SS': 'SOUTH SUDAN',
	'ES': 'SPAIN',
	'LK': 'SRI LANKA',
	'SD': 'SUDAN',
	'SR': 'SURINAME',
	'SJ': 'SVALBARD AND JAN MAYEN',
	'SZ': 'SWAZILAND',
	'SE': 'SWEDEN',
	'CH': 'SWITZERLAND',
	'SY': 'SYRIAN ARAB REPUBLIC',
	'TW': 'TAIWAN, PROVINCE OF CHINA',
	'TJ': 'TAJIKISTAN',
	'TZ': 'TANZANIA, UNITED REPUBLIC OF',
	'TH': 'THAILAND',
	'TL': 'TIMOR-LESTE',
	'TG': 'TOGO',
	'TK': 'TOKELAU',
	'TO': 'TONGA',
	'TT': 'TRINIDAD AND TOBAGO',
	'TN': 'TUNISIA',
	'TR': 'TURKEY',
	'TM': 'TURKMENISTAN',
	'TC': 'TURKS AND CAICOS ISLANDS',
	'TV': 'TUVALU',
	'UG': 'UGANDA',
	'UA': 'UKRAINE',
	'AE': 'UNITED ARAB EMIRATES',
	'GB': 'UNITED KINGDOM',
	'US': 'UNITED STATES',
	'UM': 'UNITED STATES MINOR OUTLYING ISLANDS',
	'UY': 'URUGUAY',
	'UZ': 'UZBEKISTAN',
	'VU': 'VANUATU',
	'VE': 'VENEZUELA, BOLIVARIAN REPUBLIC OF',
	'VN': 'VIET NAM',
	'VG': 'VIRGIN ISLANDS, BRITISH',
	'VI': 'VIRGIN ISLANDS, U.S.',
	'WF': 'WALLIS AND FUTUNA',
	'EH': 'WESTERN SAHARA',
	'YE': 'YEMEN',
	'ZM': 'ZAMBIA',
	'ZW': 'ZIMBABWE',
}

wc_countries = {
	'US': 'USA',
	'CN': 'China',
	'IT': 'Italy',
	'ES': 'Spain',
	'DE': 'Germany',
	'IR': 'Iran',
	'FR': 'Mayotte',
	'CH': 'Switzerland',
	'UA': 'Ukraine',
	'KR': 'S. Korea',
	'NL': 'Sint Maarten',
	'AT': 'Austria',
	'BE': 'Belgium',
	'CA': 'Canada',
	'TR': 'Turkey',
	'PT': 'Portugal',
	'NO': 'Norway',
	'BR': 'Brazil',
	'SE': 'Sweden',
	'AU': 'Australia',
	'IL': 'Israel',
	'MY': 'Malaysia',
	'CZ': 'Czechia',
	'DK': 'Denmark',
	'IE': 'Ireland',
	'LU': 'Luxembourg',
	'JP': 'Japan',
	'EC': 'Ecuador',
	'CL': 'Chile',
	'PL': 'Poland',
	'PK': 'Pakistan',
	'TH': 'Thailand',
	'RO': 'Romania',
	'SA': 'Saudi Arabia',
	'FI': 'Finland',
	'ZA': 'South Africa',
	'ID': 'Indonesia',
	'GR': 'Greece',
	'RU': 'Russia',
	'IS': 'Iceland',
	'IN': 'India',
	'PH': 'Philippines',
	'SG': 'Singapore',
	'PE': 'Peru',
	'SI': 'Slovenia',
	'PA': 'Panama',
	'QA': 'Qatar',
	'EE': 'Estonia',
	'AR': 'Argentina',
	'EG': 'Egypt',
	'HR': 'Croatia',
	'CO': 'Colombia',
	'DO': 'Dominican Republic',
	'MX': 'Mexico',
	'BH': 'Bahrain',
	'RS': 'Serbia',
	'HK': 'Hong Kong',
	'IQ': 'Iraq',
	'LB': 'Lebanon',
	'DZ': 'Algeria',
	'UAE': 'UAE',
	'LT': 'Lithuania',
	'AM': 'Armenia',
	'NZ': 'New Zealand',
	'MA': 'Morocco',
	'BG': 'Bulgaria',
	'HU': 'Hungary',
	'TW': 'Taiwan',
	'LV': 'Latvia',
	'CR': 'Costa Rica',
	'SK': 'Slovakia',
	'AD': 'Andorra',
	'UY': 'Uruguay',
	'JO': 'Jordan',
	'SM': 'San Marino',
	'KW': 'Kuwait',
	'MK': 'North Macedonia',
	'TN': 'Tunisia',
	'BA': 'Bosnia and Herzegovina',
	'MD': 'Moldova',
	'AL': 'Albania',
	'VN': 'Vietnam',
	'BF': 'Burkina Faso',
	'CY': 'Cyprus',
	'FO': 'Faeroe Islands',
	'RE': 'Réunion',
	'MT': 'Malta',
	'GH': 'Ghana',
	'AZ': 'Azerbaijan',
	'BN': 'Brunei',
	'KZ': 'Kazakhstan',
	'OM': 'Oman',
	'LK': 'Sri Lanka',
	'VE': 'Venezuela',
	'SN': 'Senegal',
	'KH': 'Cambodia',
	'CI': 'Ivory Coast',
	'AF': 'Afghanistan',
	'BY': 'Belarus',
	'PS': 'Palestine',
	'MU': 'Mauritius',
	'GE': 'Georgia',
	'CM': 'Cameroon',
	'UZ': 'Uzbekistan',
	'ME': 'Montenegro',
	'CU': 'Cuba',
	'MQ': 'Martinique',
	'NG': 'Niger',
	'TT': 'Trinidad and Tobago',
	'LI': 'Liechtenstein',
	'HN': 'Honduras',
	'CD': 'DRC',
	'BD': 'Bangladesh',
	'KG': 'Kyrgyzstan',
	'BO': 'Bolivia',
	'PY': 'Paraguay',
	'RW': 'Rwanda',
	'MC': 'Monaco',
	'KE': 'Kenya',
	'MO': 'Macao',
	'PF': 'French Polynesia',
	'GF': 'French Guiana',
	'JM': 'Jamaica',
	'GI': 'Gibraltar',
	'IM': 'Isle of Man',
	'GT': 'Guatemala',
	'MG': 'Madagascar',
	'TG': 'Togo',
	'AW': 'Aruba',
	'BB': 'Barbados',
	'ZM': 'Zambia',
	'NC': 'New Caledonia',
	'UG': 'Uganda',
	'SV': 'El Salvador',
	'MV': 'Maldives',
	'TZ': 'Tanzania',
	'GQ': 'Equatorial Guinea',
	'ET': 'Ethiopia',
	'DJ': 'Djibouti',
	'DM': 'Dominica',
	'MN': 'Mongolia',
	'MF': 'Saint Martin',
	'KY': 'Cayman Islands',
	'HT': 'Haiti',
	'NA': 'Namibia',
	'SR': 'Suriname',
	'GA': 'Gabon',
	'BM': 'Bermuda',
	'MZ': 'Mozambique',
	'SC': 'Seychelles',
	'BJ': 'Benin',
	'GL': 'Greenland',
	'LA': 'Laos',
	'GY': 'Guyana',
	'BS': 'Bahamas',
	'FJ': 'Fiji',
	'SY': 'Syria',
	'CV': 'Cabo Verde',
	'AO': 'Angola',
	'CG': 'Congo',
	'ER': 'Eritrea',
	'GN': 'Guinea',
	'VA': 'Vatican City',
	'ML': 'Mali',
	'SZ': 'Eswatini',
	'GM': 'Gambia',
	'SD': 'Sudan',
	'ZW': 'Zimbabwe',
	'NP': 'Nepal',
	'AG': 'Antigua and Barbuda',
	'NI': 'Nicaragua',
	'TD': 'Chad',
	'LR': 'Liberia',
	'MR': 'Mauritania',
	'MM': 'Myanmar',
	'BL': 'St. Barth',
	'LC': 'Saint Lucia',
	'BZ': 'Belize',
	'BT': 'Bhutan',
	'VG': 'British Virgin Islands',
	'GW': 'Guinea-Bissau',
	'MS': 'Montserrat',
	'KN': 'Saint Kitts and Nevis',
	'SO': 'Somalia',
	'TC': 'Turks and Caicos',
	'GD': 'Grenada',
	'LY': 'Libya',
	'PG': 'Papua New Guinea',
	'VC': 'St. Vincent Grenadines',
	'TL': 'Timor-Leste'
}